spring:
  datasource:
#    url: jdbc:postgresql://db:5432/search_engine
    url: jdbc:postgresql://localhost:5432/search_engine
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    show-sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework: ERROR

indexing-settings:
  sites:
    - url: https://www.lenta.ru
      name: Лента.ру
    - url: https://www.rbc.ru
      name: РБК
    - url: https://www.skillbox.ru
      name: Skillbox
    - url: https://www.playback.ru
      name: PlayBack.
